/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metasys_ryft_Wrapper */

#ifndef _Included_com_metasys_ryft_Wrapper
#define _Included_com_metasys_ryft_Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_metasys_ryft_Wrapper_init
  (JNIEnv *, jobject);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    openFile
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_openFile
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    writeIndex
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_writeIndex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    writeData
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_writeData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    search
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_search
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    fuzzySearch
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_fuzzySearch
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    sortAsc
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_sortAsc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    sortDesc
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_sortDesc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    termFrequency
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_termFrequency
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_metasys_ryft_Wrapper
 * Method:    execute
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_metasys_ryft_Wrapper_execute
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
